class ChocolateRunner{
	 public static void main(String[] args) {
        Chocolate chocolate1 = new Chocolate("Lindt", "Milk Chocolate", 100, 5.99, false, true, false, false, "Switzerland", 30.5, false, false, true, false, "Classic", "Foil", 365, false, true);
        Chocolate chocolate2 = new Chocolate("Godiva", "Dark Chocolate", 85, 7.49, false, false, true, false, "Belgium", 72.0, false, false, true, false, "Rich Cocoa", "Boxed", 300, true, true);
        Chocolate chocolate3 = new Chocolate("Cadbury", "Fruit & Nut", 150, 4.99, false, true, false, false, "UK", 25.0, false, true, false, false, "Nutty & Fruity", "Wrapper", 180, false, false);

        System.out.println("Chocolate 1: \nBrand: " + chocolate1.brand + ", \nType: " + chocolate1.type + ", \nWeight: " + chocolate1.weight + " g, \nPrice: $" + chocolate1.price + ", \nSugar Free: " + chocolate1.isSugarFree + ", \nContains Nuts: " + chocolate1.hasNuts + ", \nDark Chocolate: " + chocolate1.isDarkChocolate + ", \nVegan: " + chocolate1.isVegan + ", \nOrigin: " + chocolate1.origin + ", \nCocoa Percentage: " + chocolate1.cocoaPercentage + "%, \nHas Caramel: " + chocolate1.hasCaramel + ", \nHas Fruit: " + chocolate1.hasFruit + ", \nOrganic: " + chocolate1.isOrganic + ", \nHas Wafer: " + chocolate1.hasWafer + ", \nFlavor: " + chocolate1.flavor + ", \nPackaging: " + chocolate1.packaging + ", \nShelf Life: " + chocolate1.shelfLife + " days, \nLimited Edition: " + chocolate1.isLimitedEdition + ", \nHandcrafted: " + chocolate1.isHandcrafted + "\n");
        
        System.out.println("Chocolate 2: \nBrand: " + chocolate2.brand + ", \nType: " + chocolate2.type + ", \nWeight: " + chocolate2.weight + " g, \nPrice: $" + chocolate2.price + ", \nSugar Free: " + chocolate2.isSugarFree + ", \nContains Nuts: " + chocolate2.hasNuts + ", \nDark Chocolate: " + chocolate2.isDarkChocolate + ", \nVegan: " + chocolate2.isVegan + ", \nOrigin: " + chocolate2.origin + ", \nCocoa Percentage: " + chocolate2.cocoaPercentage + "%, \nHas Caramel: " + chocolate2.hasCaramel + ", \nHas Fruit: " + chocolate2.hasFruit + ", \nOrganic: " + chocolate2.isOrganic + ", \nHas Wafer: " + chocolate2.hasWafer + ", \nFlavor: " + chocolate2.flavor + ", \nPackaging: " + chocolate2.packaging + ", \nShelf Life: " + chocolate2.shelfLife + " days, \nLimited Edition: " + chocolate2.isLimitedEdition + ", \nHandcrafted: " + chocolate2.isHandcrafted + "\n");
        
        System.out.println("Chocolate 3: \nBrand: " + chocolate3.brand + ", \nType: " + chocolate3.type + ", \nWeight: " + chocolate3.weight + " g, \nPrice: $" + chocolate3.price + ", \nSugar Free: " + chocolate3.isSugarFree + ", \nContains Nuts: " + chocolate3.hasNuts + ", \nDark Chocolate: " + chocolate3.isDarkChocolate + ", \nVegan: " + chocolate3.isVegan + ", \nOrigin: " + chocolate3.origin + ", \nCocoa Percentage: " + chocolate3.cocoaPercentage + "%, \nHas Caramel: " + chocolate3.hasCaramel + ", \nHas Fruit: " + chocolate3.hasFruit + ", \nOrganic: " + chocolate3.isOrganic + ", \nHas Wafer: " + chocolate3.hasWafer + ", \nFlavor: " + chocolate3.flavor + ", \nPackaging: " + chocolate3.packaging + ", \nShelf Life: " + chocolate3.shelfLife + " days, \nLimited Edition: " + chocolate3.isLimitedEdition + ", \nHandcrafted: " + chocolate3.isHandcrafted + "\n");
    }
}