class DroneRunner{
	public static void main(String[] args) {
        Drone drone1 = new Drone("DJI", "Mavic Air 2", 570, 34, 19, 10, "48MP, 4K Video", true, true, true, "3500mAh", "Remote & App", true, false, "Photography", false, 2, 999.99, true);
        Drone drone2 = new Drone("Parrot", "Anafi", 320, 25, 15, 4, "21MP, 4K HDR Video", true, false, true, "2700mAh", "Remote", true, false, "Cinematic Filming", false, 1, 699.99, false);
        Drone drone3 = new Drone("Autel", "Evo II", 1150, 40, 20, 9, "48MP, 8K Video", true, true, false, "7100mAh", "Remote", true, true, "Industrial Inspection", true, 3, 1799.99, true);

        System.out.println("Drone 1: " + drone1.brand + ", Model: " + drone1.model + ", Weight: " + drone1.weight + "g, Max Flight Time: " + drone1.maxFlightTime + " mins, Max Speed: " + drone1.maxSpeed + " m/s, Range: " + drone1.range + " km, Camera: " + drone1.cameraSpecs + ", GPS: " + drone1.hasGPS + ", Obstacle Avoidance: " + drone1.hasObstacleAvoidance + ", Foldable: " + drone1.isFoldable + ", Battery: " + drone1.batteryCapacity + ", Remote Control: " + drone1.remoteControlType + ", Live Streaming: " + drone1.supportsLiveStreaming + ", Night Vision: " + drone1.hasNightVision + ", Usage: " + drone1.usage + ", Waterproof: " + drone1.isWaterproof + ", Warranty: " + drone1.warrantyYears + " years, Price: $" + drone1.price + ", VR Support: " + drone1.supportsVR);
        System.out.println();
        System.out.println("Drone 2: " + drone2.brand + ", Model: " + drone2.model + ", Weight: " + drone2.weight + "g, Max Flight Time: " + drone2.maxFlightTime + " mins, Max Speed: " + drone2.maxSpeed + " m/s, Range: " + drone2.range + " km, Camera: " + drone2.cameraSpecs + ", GPS: " + drone2.hasGPS + ", Obstacle Avoidance: " + drone2.hasObstacleAvoidance + ", Foldable: " + drone2.isFoldable + ", Battery: " + drone2.batteryCapacity + ", Remote Control: " + drone2.remoteControlType + ", Live Streaming: " + drone2.supportsLiveStreaming + ", Night Vision: " + drone2.hasNightVision + ", Usage: " + drone2.usage + ", Waterproof: " + drone2.isWaterproof + ", Warranty: " + drone2.warrantyYears + " years, Price: $" + drone2.price + ", VR Support: " + drone2.supportsVR);
        System.out.println();
        System.out.println("Drone 3: " + drone3.brand + ", Model: " + drone3.model + ", Weight: " + drone3.weight + "g, Max Flight Time: " + drone3.maxFlightTime + " mins, Max Speed: " + drone3.maxSpeed + " m/s, Range: " + drone3.range + " km, Camera: " + drone3.cameraSpecs + ", GPS: " + drone3.hasGPS + ", Obstacle Avoidance: " + drone3.hasObstacleAvoidance + ", Foldable: " + drone3.isFoldable + ", Battery: " + drone3.batteryCapacity + ", Remote Control: " + drone3.remoteControlType + ", Live Streaming: " + drone3.supportsLiveStreaming + ", Night Vision: " + drone3.hasNightVision + ", Usage: " + drone3.usage + ", Waterproof: " + drone3.isWaterproof + ", Warranty: " + drone3.warrantyYears + " years, Price: $" + drone3.price + ", VR Support: " + drone3.supportsVR);
    }
}
