class PaintBrushRunner{
	public static void main(String[] args) {
        PaintBrush brush1 = new PaintBrush("Winsor & Newton", "Natural", "Wood", 15.5, true, "Round", true, false, "Acrylic Painting", "Brown", false, true, "Professional", 0.05, false, true, 2, 12.99, true);
        PaintBrush brush2 = new PaintBrush("Da Vinci", "Synthetic", "Plastic", 12.0, true, "Flat", true, true, "Watercolor", "Blue", true, true, "Hobby", 0.03, false, false, 1, 8.49, true);
        PaintBrush brush3 = new PaintBrush("Royal & Langnickel", "Blend", "Bamboo", 14.2, true, "Fan", false, false, "Oil Painting", "Black", true, true, "Artist", 0.06, false, true, 3, 15.99, true);

        System.out.println("PaintBrush 1: \nbrand" + brush1.brand + ", \nbristleMaterial" + brush1.bristleMaterial + ", \nhandleMaterial" + brush1.handleMaterial + ", \nlength" + brush1.length + " cm, \nisWashable" + brush1.isWashable + ", \nshape" + brush1.shape + ", \nhasComfortGrip" + brush1.hasComfortGrip + ", \nhasReplaceableBristles" + brush1.hasReplaceableBristles + ", \napplication" + brush1.application + ", \ncolor" + brush1.color + ", \nisSynthetic" + brush1.isSynthetic + ", \nisEcoFriendly" + brush1.isEcoFriendly + ", \nusageType" + brush1.usageType + ", \nweight" + brush1.weight + " kg, \nisDoubleSided" + brush1.isDoubleSided + ", \nhasProtectiveCover" + brush1.hasProtectiveCover + ", \nwarrantyYears" + brush1.warrantyYears + " years, \nprice" + brush1.price + ", \nhasAntiSheddingBristles" + brush1.hasAntiSheddingBristles);
        System.out.println();
        System.out.println("PaintBrush 2: \nbrand" + brush2.brand + ", \nbristleMaterial" + brush2.bristleMaterial + ", \nhandleMaterial" + brush2.handleMaterial + ", \nlength" + brush2.length + " cm, \nisWashable" + brush2.isWashable + ", \nshape" + brush2.shape + ", \nhasComfortGrip" + brush2.hasComfortGrip + ", \nhasReplaceableBristles" + brush2.hasReplaceableBristles + ", \napplication" + brush2.application + ", \ncolor" + brush2.color + ", \nisSynthetic" + brush2.isSynthetic + ", \nisEcoFriendly" + brush2.isEcoFriendly + ", \nusageType" + brush2.usageType + ", \nweight" + brush2.weight + " kg, \nisDoubleSided" + brush2.isDoubleSided + ", \nhasProtectiveCover" + brush2.hasProtectiveCover + ", \nwarrantyYears" + brush2.warrantyYears + " years, \nprice" + brush2.price + ", \nhasAntiSheddingBristles" + brush2.hasAntiSheddingBristles);
        System.out.println();
        System.out.println("PaintBrush 3: \nbrand" + brush3.brand + ", \nbristleMaterial" + brush3.bristleMaterial + ", \nhandleMaterial" + brush3.handleMaterial + ", \nlength" + brush3.length + " cm, \nisWashable" + brush3.isWashable + ", \nshape" + brush3.shape + ", \nhasComfortGrip" + brush3.hasComfortGrip + ", \nhasReplaceableBristles" + brush3.hasReplaceableBristles + ", \napplication" + brush3.application + ", \ncolor" + brush3.color + ", \nisSynthetic" + brush3.isSynthetic + ", \nisEcoFriendly" + brush3.isEcoFriendly + ", \nusageType" + brush3.usageType + ", \nweight" + brush3.weight + " kg, \nisDoubleSided" + brush3.isDoubleSided + ", \nhasProtectiveCover" + brush3.hasProtectiveCover + ", \nwarrantyYears" + brush3.warrantyYears + " years, \nprice" + brush3.price + ", \nhasAntiSheddingBristles" + brush3.hasAntiSheddingBristles);
    }
}