class PlanetRunner{
	public static void main(String[] args) {
        Planet planet1 = new Planet("Earth", 5.972e24, 6371, 9.81, "Terrestrial", "Nitrogen, Oxygen", false, 1, "Ancient", "Unknown", 365.25, 24, 149.6e6, true, "Iron-Nickel", 288, "Oceans, Mountains, Deserts", true, "Apollo, Voyager", "Habitable");
        Planet planet2 = new Planet("Mars", 0.64171e24, 3389.5, 3.72076, "Terrestrial", "Carbon Dioxide, Nitrogen", false, 2, "Ancient", "Unknown", 687, 24.6, 227.9e6, false, "Iron, Sulfur", 210, "Canyons, Volcanoes, Ice Caps", true, "Curiosity, Perseverance", "Rocky");
        Planet planet3 = new Planet("Jupiter", 1.898e27, 69911, 24.79, "Gas Giant", "Hydrogen, Helium", true, 79, "Ancient", "Unknown", 4333, 9.9, 778.5e6, false, "Metallic Hydrogen", 165, "Storms, Bands, Red Spot", true, "Juno, Galileo", "Gas Giant");

        System.out.println("Planet 1: " + planet1.name + ", Mass: " + planet1.mass + " kg, Radius: " + planet1.radius + " km, Gravity: " + planet1.gravity + " m/s^2, Type: " + planet1.type + ", Atmosphere: " + planet1.atmosphere + ", Rings: " + planet1.hasRings + ", Moons: " + planet1.numberOfMoons + ", Discovery: " + planet1.discoveryDate + ", Discovered By: " + planet1.discoveredBy + ", Orbital Period: " + planet1.orbitalPeriod + " days, Rotation Period: " + planet1.rotationPeriod + " hours, Distance from Sun: " + planet1.distanceFromSun + " km, Supports Life: " + planet1.supportsLife + ", Core: " + planet1.coreComposition + ", Surface Temp: " + planet1.surfaceTemperature + " K, Surface Features: " + planet1.surfaceFeatures + ", Magnetic Field: " + planet1.hasMagneticField + ", Space Missions: " + planet1.spaceMissions + ", Category: " + planet1.planetCategory);
        
        System.out.println("Planet 2: " + planet2.name + ", Mass: " + planet2.mass + " kg, Radius: " + planet2.radius + " km, Gravity: " + planet2.gravity + " m/s^2, Type: " + planet2.type + ", Atmosphere: " + planet2.atmosphere + ", Rings: " + planet2.hasRings + ", Moons: " + planet2.numberOfMoons + ", Discovery: " + planet2.discoveryDate + ", Discovered By: " + planet2.discoveredBy + ", Orbital Period: " + planet2.orbitalPeriod + " days, Rotation Period: " + planet2.rotationPeriod + " hours, Distance from Sun: " + planet2.distanceFromSun + " km, Supports Life: " + planet2.supportsLife + ", Core: " + planet2.coreComposition + ", Surface Temp: " + planet2.surfaceTemperature + " K, Surface Features: " + planet2.surfaceFeatures + ", Magnetic Field: " + planet2.hasMagneticField + ", Space Missions: " + planet2.spaceMissions + ", Category: " + planet2.planetCategory);
        
        System.out.println("Planet 3: " + planet3.name + ", Mass: " + planet3.mass + " kg, Radius: " + planet3.radius + " km, Gravity: " + planet3.gravity + " m/s^2, Type: " + planet3.type + ", Atmosphere: " + planet3.atmosphere + ", Rings: " + planet3.hasRings + ", Moons: " + planet3.numberOfMoons + ", Discovery: " + planet3.discoveryDate + ", Discovered By: " + planet3.discoveredBy + ", Orbital Period: " + planet3.orbitalPeriod + " days, Rotation Period: " + planet3.rotationPeriod + " hours, Distance from Sun: " + planet3.distanceFromSun + " km, Supports Life: " + planet3.supportsLife + ", Core: " + planet3.coreComposition + ", Surface Temp: " + planet3.surfaceTemperature + " K, Surface Features: " + planet3.surfaceFeatures + ", Magnetic Field: " + planet3.hasMagneticField + ", Space Missions: " + planet3.spaceMissions + ", Category: " + planet3.planetCategory);
    }

}