class RocketRunner{
	public static void main(String[] args) {
        Rocket rocket1 = new Rocket("Falcon 9", "SpaceX", 70, 3.7, 549054, 2, 7607, 22800, "RP-1/LOX", "2006-03-24", true, "Cape Canaveral", true, "Orbital", "ISS", "USA", 150, 10, "Crew Dragon, Starlink", 62.0);
        Rocket rocket2 = new Rocket("Saturn V", "NASA", 110.6, 10.1, 2970000, 3, 35100, 140000, "RP-1/LOX, LH2/LOX", "1967-11-09", false, "Kennedy Space Center", false, "Lunar", "Moon", "USA", 13, 0, "Apollo 11, Apollo 17", 185.0);
        Rocket rocket3 = new Rocket("Soyuz", "Roscosmos", 50, 2.95, 305000, 3, 1020, 7100, "Kerosene/LOX", "1966-11-28", false, "Baikonur Cosmodrome", true, "Orbital", "LEO", "Russia", 1800, 50, "Soyuz MS, Progress", 45.0);

        System.out.println("Rocket 1: " + rocket1.name + ", Manufacturer: " + rocket1.manufacturer + ", Height: " + rocket1.height + " m, Diameter: " + rocket1.diameter + " m, Mass: " + rocket1.mass + " kg, Stages: " + rocket1.stages + ", Thrust: " + rocket1.thrust + " kN, Payload: " + rocket1.payloadCapacity + " kg, Fuel: " + rocket1.fuelType + ", Launch Date: " + rocket1.launchDate + ", Reusable: " + rocket1.isReusable + ", Launch Site: " + rocket1.launchSite + ", Escape System: " + rocket1.hasEscapeSystem + ", Mission: " + rocket1.missionType + ", Destination: " + rocket1.destination + ", Country: " + rocket1.country + ", Successes: " + rocket1.successfulLaunches + ", Failures: " + rocket1.failedLaunches + ", Notable Missions: " + rocket1.notableMissions + ", Cost: $" + rocket1.cost + "M");
        System.out.println();
        System.out.println("Rocket 2: " + rocket2.name + ", Manufacturer: " + rocket2.manufacturer + ", Height: " + rocket2.height + " m, Diameter: " + rocket2.diameter + " m, Mass: " + rocket2.mass + " kg, Stages: " + rocket2.stages + ", Thrust: " + rocket2.thrust + " kN, Payload: " + rocket2.payloadCapacity + " kg, Fuel: " + rocket2.fuelType + ", Launch Date: " + rocket2.launchDate + ", Reusable: " + rocket2.isReusable + ", Launch Site: " + rocket2.launchSite + ", Escape System: " + rocket2.hasEscapeSystem + ", Mission: " + rocket2.missionType + ", Destination: " + rocket2.destination + ", Country: " + rocket2.country + ", Successes: " + rocket2.successfulLaunches + ", Failures: " + rocket2.failedLaunches + ", Notable Missions: " + rocket2.notableMissions + ", Cost: $" + rocket2.cost + "M");
        System.out.println();
        System.out.println("Rocket 3: " + rocket3.name + ", Manufacturer: " + rocket3.manufacturer + ", Height: " + rocket3.height + " m, Diameter: " + rocket3.diameter + " m, Mass: " + rocket3.mass + " kg, Stages: " + rocket3.stages + ", Thrust: " + rocket3.thrust + " kN, Payload: " + rocket3.payloadCapacity + " kg, Fuel: " + rocket3.fuelType + ", Launch Date: " + rocket3.launchDate + ", Reusable: " + rocket3.isReusable + ", Launch Site: " + rocket3.launchSite + ", Escape System: " + rocket3.hasEscapeSystem + ", Mission: " + rocket3.missionType + ", Destination: " + rocket3.destination + ", Country: " + rocket3.country + ", Successes: " + rocket3.successfulLaunches + ", Failures: " + rocket3.failedLaunches + ", Notable Missions: " + rocket3.notableMissions + ", Cost: $" + rocket3.cost + "M");
    }
}

